### ISSUE TITLE
После загрузки непонятно, какую версию использовать.

### ISSUE THREAD

**Issue by stealzy** [LongSoft/FTK#1]
Предлагаю добавить в корень архива текстовый файл:
What version use.txt / Readme.txt
Version FTK depends of your intel chipset version:
For C20x chipset - 7.xx
For desktops and servers with Z87, H87, B85, Q87, Q85, C220 chipset - 9.00
For notebooks with HM87, QM87, QM86 chipset - 9.5
For all other chipset 6 and 7 series - 8.00

**Comment by minzak** [comment]
Все начиная с 7й версии (
А 6я есть? Поддерживается?

Хочу понизить версию с 6.2.6 до 6.2.4:
FWUpdLcl.exe PCH_8M_MB_UPD_Production.BIN -generic -allowsv
Intel (R) Firmware Update Utility Version 6.2.0.1022
Copyright (C) 2007-2011, Intel Corporation.  All rights reserved.
Error 8705: Firmware update not initiated due to version mismatch
